### ISSUE TITLE
BugFix: Change orientation while places are loading

### ISSUE THREAD

**Issue by deforation** [samwisee/Sights#33]
The app does not behave as expected, when one is in portrait mode and the orientation is changed while it is loading the places.

It stops loading and afterwords it is not possible, to load the places again.

**Comment by samwisee** [comment]
The same problem seems to occur, if a place is clicked before all places are loaded. maybe has todo with running (or pending) asynctasks that should be cancelled or so

**Comment by deforation** [comment]
Problems fixed:

Cause:
  AsyncTasks had to be moved to the Fragment.

  setRetainInstance was set to true for the fragment. (So it is kept in the ram and not complete cleard)

  GoogleApiClient was moved to a singleton class. (Because frament needed one and the main activity)
  There were different problems, when the Client was created in the main activity or in the fragment.
  Example: Autocomplete stopped working, Orientation change broke the loading process,...

  AsyncTasks can now update or add a new POI to the list.
  Necessary, when the screen orientation is changed immediatelly after starting the search.
  So the adapter had an list with only a few elements and if they are only updated, some entries would 
  be missing.

  Fixed issue, where unknown distance was not shown due to api problems,...
  And a fix, after the adapter had loaded the data from the json file.
  So it showed no text, because the isDistanceSet flag was not set

  MainActivity implements a new listener where he gets informed, when a search progess starts
  or ends. Needed, when the orientation is changed immediatelly after the search.
  So there are no problems with the loading symbol

  Other small fixes.
